name: Build YTLitePlus

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct download link to decrypted YouTube IPA'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download IPA
        run: |
          curl -L "${{ github.event.inputs.ipa_url }}" -o YouTube.ipa

      - name: Run patch script
        run: |
          chmod +x patch.sh
          ./patch.sh YouTube.ipa

      - name: Upload patched IPA
        uses: actions/upload-artifact@v2
        with:
          name: YTLitePlus
          path: YTLitePlus.ipa
