name: Build YTLitePlus

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct download link to decrypted YouTube IPA'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git clang ldid make dpkg curl

      - name: Install Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV
          echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV

      - name: Download decrypted IPA
        run: curl -L "${{ github.event.inputs.ipa_url }}" -o YouTube.ipa

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh YouTube.ipa

      - name: List contents of packages folder
        run: ls -la YTLitePlus/packages || echo "No packages folder found"

      - name: Upload patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: YTLitePlus
          path: YTLitePlus/packages/*.ipa
