name: Build YTLitePlus

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct download link to decrypted YouTube IPA'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download decrypted IPA
        run: |
          curl -L "${{ github.event.inputs.ipa_url }}" -o YouTube.ipa

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh YouTube.ipa

        - name: List contents of YTLitePlus/packages
  run: ls -la YTLitePlus/packages || echo "Directory not found"


      - name: Upload patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: YTLitePlus
          path: YTLitePlus/packages/*.ipa
