name: Build YTLitePlus

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct download link to decrypted YouTube IPA'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git clang make dpkg curl devscripts
          echo "Verifying devscripts installation:"
          dpkg -l | grep devscripts || echo "devscripts not found"
          which dm.pl || echo "dm.pl not found"

      - name: Fix dm.pl path
        run: |
          DMPL_PATH=$(find /usr -name dm.pl | head -n 1)
          echo "Found dm.pl at: $DMPL_PATH"
          if [ -n "$DMPL_PATH" ]; then
            sudo ln -sf "$DMPL_PATH" /usr/bin/dm.pl
          else
            echo "dm.pl not found anywhere"
            exit 1
          fi

      - name: Install Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV
          echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV

      - name: Download decrypted IPA
        run: curl -L "${{ github.event.inputs.ipa_url }}" -o YouTube.ipa

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script
        run: ./build.sh YouTube.ipa

      - name: List contents of packages folder
        run: ls -la YTLitePlus/packages || echo "No packages folder found"

      - name: Upload patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: YTLitePlus
          path: YTLitePlus/packages/*.ipa
